/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel;

import javax.swing.ImageIcon;
import javax.swing.JRadioButton;

/**
 *
 * @author nerix
 */
public class BotonTamanoProducto extends javax.swing.JPanel {

    private String tamano;
    private ImageIcon imagenTamano;
    //private Producto producto;
    
    /**
     * Creates new form BotonTamanoProducto
     */
    public BotonTamanoProducto(String tamano) {
        initComponents();
        
        this.tamano = tamano;
        this.tamanoProductoBtn.setText(tamano);
    }
    
    public void setImagenTamano(ImageIcon imagen) {
        this.imagenTamano = imagen;
        this.imagenTamanoProducto.setIcon(imagen);
        this.imagenTamanoProducto.revalidate();
        this.imagenTamanoProducto.repaint();
    }
            
    public JRadioButton getJRadioButton() {
        return this.tamanoProductoBtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tamanoProductoBtn = new javax.swing.JRadioButton();
        imagenTamanoProducto = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(100, 100));

        tamanoProductoBtn.setBackground(java.awt.SystemColor.control);
        tamanoProductoBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tamanoProductoBtn.setText("Tamano");

        imagenTamanoProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagenTamanoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tamanoProductoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenTamanoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tamanoProductoBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenTamanoProducto;
    private javax.swing.JRadioButton tamanoProductoBtn;
    // End of variables declaration//GEN-END:variables
}
