/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.ComplementoDTO;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.OpcionComplementoDTO;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.FrameRealizarPedido;

/**
 * Tarjetas que se muestran con botones de agregar o quitar para la eleccion de complemetos.
 * @author Saul Neri
 */
public class ComplementoPanel extends javax.swing.JPanel {

    private ComplementoDTO complemento;
    private int cantidadActual = 0;
    private float costoTotal = 0.0f;

    private FrameRealizarPedido parent;
    private SeleccionComplementosPanel seleccionPanel;

    /**
     * Creates new form ComplementoPanel
     */
    public ComplementoPanel(FrameRealizarPedido parent, SeleccionComplementosPanel seleccionPanel, ComplementoDTO complemento) {
        initComponents();

        this.seleccionPanel = seleccionPanel;
        
        this.complemento = complemento;
        this.cantidadActual = 0;
        this.parent = parent;

        this.nombreComplementoLabel.setText(this.complemento.nombre);
        this.cantidadActualLabel.setText("0");

        this.quitarComplementoBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cantidadActual--;

                if (cantidadActual < 0) {
                    cantidadActual = 0;
                    cantidadActualLabel.setText("0");
                    return;
                }

                seleccionPanel.recalcularMontoTotal();
                
                //parent.actualizarMontoTotalDetallePedido();

                System.out.println("quitar!!!: " + cantidadActual);

                recalcularCostoTotal();
            }
        });

        this.agregarComplementoBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                cantidadActual++;

                seleccionPanel.recalcularMontoTotal();
                
                //parent.actualizarMontoTotalDetallePedido();

                System.out.println("agregar!!!: " + cantidadActual);

                recalcularCostoTotal();
            }
        });
    }
    
    /**
     * Obtiene una opcion de complemento si es que la cantidad seleccionada es 
     * mas de 1.
     * @return OpcionComplementoDTO opcion
     */
    public OpcionComplementoDTO obtenerOpcionComplemento() {
        if (this.cantidadActual > 0) {
            return new OpcionComplementoDTO(this.complemento, this.cantidadActual);
        }

        return null;
    }

    /**
     * Recalcula y muestra en la misma tarjeta el nuevo precio por la nueva 
     * cantidad elegida de complementos.
     */
    private void recalcularCostoTotal() {
        cantidadActualLabel.setText(Integer.toString(cantidadActual));
        costoTotal = this.complemento.precio * cantidadActual;
        costoTotalComplementoLabel.setText(String.format("$%.2f", costoTotal));

        this.cantidadActualLabel.revalidate();
        this.cantidadActualLabel.repaint();
        this.costoTotalComplementoLabel.revalidate();
        this.costoTotalComplementoLabel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        nombreComplementoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel(new FlowLayout(FlowLayout.RIGHT));
        agregarComplementoBtn = new javax.swing.JButton();
        cantidadActualLabel = new javax.swing.JLabel();
        quitarComplementoBtn = new javax.swing.JButton();
        costoTotalComplementoLabel = new javax.swing.JLabel();

        jButton2.setText("+");

        nombreComplementoLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nombreComplementoLabel.setText("Nombre del Complemento");

        agregarComplementoBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        agregarComplementoBtn.setText("+");

        cantidadActualLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        cantidadActualLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadActualLabel.setText("0");

        quitarComplementoBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        quitarComplementoBtn.setText("-");

        costoTotalComplementoLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        costoTotalComplementoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        costoTotalComplementoLabel.setText("$0.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 113, Short.MAX_VALUE)
                .addComponent(costoTotalComplementoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quitarComplementoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadActualLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarComplementoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cantidadActualLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarComplementoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitarComplementoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(costoTotalComplementoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreComplementoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreComplementoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarComplementoBtn;
    private javax.swing.JLabel cantidadActualLabel;
    private javax.swing.JLabel costoTotalComplementoLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreComplementoLabel;
    private javax.swing.JButton quitarComplementoBtn;
    // End of variables declaration//GEN-END:variables
}
