/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel;

import mx.edu.itson.cafeteriauniversitaria.dtonegocios.DetallePedidoDTO;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.OpcionComplementoDTO;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.util.PedidoHandler;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.FrameRealizarPedido;

/**
 * Panel de confirmacion para anadir un nuevo producto al pedido.
 * @author Saul Neri
 */
public class ConfirmacionAdicionProductoPanel extends javax.swing.JPanel {

    private FrameRealizarPedido parent;
    //private DetallePedidoDTO detalle = pedido.getDetalleActual();

    private PedidoHandler pedido = PedidoHandler.getInstance();
    
    private DetallePedidoDTO detalle;

    /**
     * Creates new form ConfirmacionAdicionProductoPanel
     */
    public ConfirmacionAdicionProductoPanel(FrameRealizarPedido parent) {
        initComponents();
        this.parent = parent;

        // 2. GUARDA EL DETALLE BUENO EN TU VARIABLE DE INSTANCIA
        // (Este es el único momento en que sabes que pedido.getDetalleActual() es correcto)
        this.detalle = pedido.getDetalleActual(); 

        // 3. USA 'this.detalle' (tu variable) EN LUGAR DE 'pedido.getDetalleActual()'
        
        // Esto usa tu variable 'this.detalle'
        System.out.println(this.detalle.complementos); // (Tu Log 4)
        this.productoResumenLabel.setText(this.detalle.toString());

        //this.parent.actualizarMontoTotalDetallePedido();
        
        // Pásale 'this.detalle' al método para que también lo use
        this.cargarComplementosLabel(this.detalle);
    }

    // 4. Modifica el método para que reciba el detalle
    private void cargarComplementosLabel(DetallePedidoDTO detalle) {
        // 5. Usa el objeto 'detalle' que recibiste, NO llames a pedido.getDetalleActual()
        if (detalle == null || detalle.complementos == null || detalle.complementos.isEmpty()) {
            this.complementosLabel.setText("Sin complementos");
        } else {
            String texto = "<html>";
            // Itera sobre el detalle recibido
            for (OpcionComplementoDTO complemento : detalle.complementos) { 
                texto += String.format("%s x%d<br>",
                        complemento.complemento.nombre,
                        complemento.cantidad);
            }
            texto += "</html>";
            this.complementosLabel.setText(texto);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        confirmarProductoPedidoBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();
        productoResumenLabel = new javax.swing.JLabel();
        complementosLabel = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("¿Desea agregar este producto al pedido?");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("¿Desea agregar este producto al pedido?");

        confirmarProductoPedidoBtn.setText("Confirmar");
        confirmarProductoPedidoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarProductoPedidoBtnActionPerformed(evt);
            }
        });

        atrasBtn.setText("Atras");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atrasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmarProductoPedidoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atrasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(confirmarProductoPedidoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        productoResumenLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        productoResumenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productoResumenLabel.setText("Iced Latte (Grande) - $100.00");

        complementosLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        complementosLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        complementosLabel.setText("jLabel4");
        complementosLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productoResumenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(complementosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(productoResumenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(complementosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        //this.parent.actualizarMontoTotalDetallePedido();
        //this.parent.mostrarComplementosPanel();
    }//GEN-LAST:event_atrasBtnActionPerformed

    private void confirmarProductoPedidoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarProductoPedidoBtnActionPerformed
        // Usa this.detalle en lugar de pedido.getDetalleActual()
        this.pedido.agregarDetallePedido(this.detalle); 
        this.pedido.reiniciarDetalleActual();
        
        System.out.println("Detalles pedido: " + this.pedido.getDetallesPedido().size());
        
        // ¡Importante! Reinicia el detalle DESPUÉS de agregarlo y ANTES de salir.
        //this.pedido.reiniciarDetalleActual(); 
        //this.parent.actualizarListaPedido();
        //this.parent.mostrarProductosPanel();
    }//GEN-LAST:event_confirmarProductoPedidoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JLabel complementosLabel;
    private javax.swing.JButton confirmarProductoPedidoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productoResumenLabel;
    // End of variables declaration//GEN-END:variables
}
