/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel;

import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.util.ImageResizer;

import mx.edu.itson.cafeteriauniversitaria.dtonegocios.v1.ProductoDTO;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 * Panel que se muestra con una imagen y nombre del producto en el panel 
 * "@ProductosPanel".
 * @author Saul Neri
 */
public class ProductoPanel extends javax.swing.JPanel {

    private ProductoDTO producto;
    private ImageIcon productoImage;
    private ProductosPanel parent;
    
    /**
     * Crea un nuevo panel de producto ligado al contenedor padre para habilitar o deshabilitar
     * la opcion para pasar al siguiente frame.
     * @param parent Contenedor padre de las tarjetas de producto
     * @param producto Informacion del producto a mostrar
     */
    public ProductoPanel(ProductosPanel parent, ProductoDTO producto) {
        initComponents();
        
        this.producto = producto;
        this.parent = parent;
        
        
        try {
            this.productoImage = new ImageIcon(producto.getImagenUri());
            ImageIcon resized = ImageResizer.resize(this.productoImage, new Dimension(172,172));
            this.imagenProductoLabel.setIcon(resized);
        } catch (Exception ex) {
            Logger.getLogger(ProductoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        MouseAdapter clickAction = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.out.println("Panel clickeado: " + producto.nombre);
                parent.habilitarBotonSiguiente(producto);
            }
        };
        
        this.nombreProductoLabel.setText(producto.nombre);
        
        this.addMouseListener(clickAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenProductoLabel = new javax.swing.JLabel();
        nombreProductoLabel = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));
        setMaximumSize(new java.awt.Dimension(172, 195));
        setMinimumSize(new java.awt.Dimension(172, 195));

        nombreProductoLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nombreProductoLabel.setText("Nombre del Producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenProductoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreProductoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagenProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreProductoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenProductoLabel;
    private javax.swing.JLabel nombreProductoLabel;
    // End of variables declaration//GEN-END:variables
}
