package mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel;

import java.awt.Dimension;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.observadores.SeleccionProductoObserver;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.observadores.VolverAtrasObserver;

import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel.interfaces.ComponenteNavegable;

import mx.edu.itson.cafeteriauniversitaria.dtonegocios.v1.ProductoDTO;

import java.awt.GridLayout;
import java.util.List;

/**
 * Panel en el cual se muestran todos los productos en paneles de tipo
 * "@ProductoPanel".
 *
 * @author Saul Neri
 */
public class ProductosPanel extends javax.swing.JPanel implements ComponenteNavegable {

    /**
     * Lista de productos a mostrar en el panel.
     */
    private List<ProductoDTO> productos;

    /**
     * Producto seleccionado por el usuario.
     */
    private ProductoDTO productoSeleccionado;

    /**
     * Observador de seleccion de producto del panel.
     */
    private SeleccionProductoObserver observador;

    /**
     * Observador para el manejo del flujo de componentes.
     */
    private VolverAtrasObserver flujoPanelesObserver;

    /**
     * Crea un nuevo panel que muestra los productos disponibles en el sistema
     * en forma de cartas seleccionables.
     *
     * @param productos Lista de productos a mostrar en el panel.
     */
    public ProductosPanel(List<ProductoDTO> productos) {
        initComponents();

        this.productos = productos;

        //this.setPreferredSize(new Dimension(350, 200));
        //this.listaProductosGrid.setLayout(new GridLayout(0, 3, 10, 10));
        this.listaProductosGrid.setLayout(new GridLayout(3, 2, 10, 10));
       
        this.listaProductosGrid.setPreferredSize(null); // Asegura que no tenga un tamaño preferido fijo.

        this.cargarProductos();
    }

    /**
     * Asigna el observador del panel para detectar una seleccion de producto.
     *
     * @param observador Observador de la seleccion de producto.
     */
    public void setObservador(SeleccionProductoObserver observador) {
        this.observador = observador;
    }

    /**
     * Carga las tarjetas a traves de la lista de productos recibida y los
     * muestra en paneles de tipo "@ProductoPanel".
     */
    private void cargarProductos() {

        // 1. Limpiar el panel por si ya tenía componentes.
        this.listaProductosGrid.removeAll();

        // 2. Iterar y agregar los componentes de producto.
        if (productos != null) {

            System.out.println("Productos cargados: " + productos.size());
            
            for (ProductoDTO producto : productos) {
                // Suponiendo que tienes una clase ProductoPanel para cada producto.
                ProductoPanel panelProducto = new ProductoPanel(this, producto);
                this.listaProductosGrid.add(panelProducto);
            }
        }

        System.out.println("elementos en lista: " + this.listaProductosGrid.getComponents().length);
        
        // 3. Forzar el recálculo y repintado (¡ESTO ES CLAVE!)
        this.listaProductosGrid.revalidate(); // Recalcula el layout
        this.listaProductosGrid.repaint();   // Vuelve a pintar el componente

        // Asegúrate de que el JScrollPane también sepa que su contenido cambió.
        this.jScrollPane1.revalidate();
        this.jScrollPane1.repaint();
    }

    @Override
    public void setVolverAtrasObserver(VolverAtrasObserver observador) {
        this.flujoPanelesObserver = observador;
    }

    /**
     * Usado por ProductoPanel para habilitar el boton "Siguiente" de este panel
     * (ProductosPanel).
     *
     * @param productoSeleccionado Producto del "ProductoPanel" seleccionado.
     */
    public void habilitarBotonSiguiente(ProductoDTO productoSeleccionado) {
        this.productoSeleccionado = productoSeleccionado;
        this.siguientePanelBtn.setEnabled(true);
        this.seleccionadoLabel.setText("Seleccionado: " + productoSeleccionado.nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductosGrid = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        seleccionadoLabel = new javax.swing.JLabel();
        siguientePanelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout listaProductosGridLayout = new javax.swing.GroupLayout(listaProductosGrid);
        listaProductosGrid.setLayout(listaProductosGridLayout);
        listaProductosGridLayout.setHorizontalGroup(
            listaProductosGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        listaProductosGridLayout.setVerticalGroup(
            listaProductosGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaProductosGrid);

        seleccionadoLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seleccionadoLabel.setText("Seleccionado: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seleccionadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seleccionadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        siguientePanelBtn.setText("Siguiente");
        siguientePanelBtn.setEnabled(false);
        siguientePanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientePanelBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(siguientePanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siguientePanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void siguientePanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientePanelBtnActionPerformed
        if (this.observador != null) {
            this.observador.onProductoSeleccionado(this.productoSeleccionado);
        }
    }//GEN-LAST:event_siguientePanelBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listaProductosGrid;
    private javax.swing.JLabel seleccionadoLabel;
    private javax.swing.JButton siguientePanelBtn;
    // End of variables declaration//GEN-END:variables

}
