package mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.FrameRealizarPedido;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.util.PedidoHandler;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.OpcionComplementoDTO;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.ComplementoDTO;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.ProductoDTO;

/**
 * Panel que muestra todas las opciones de complemento disponibles en paneles 
 * de tipo "@ComplementoPanel".
 * @author Saul Neri
 */
public class SeleccionComplementosPanel extends javax.swing.JPanel {

    private FrameRealizarPedido parent;
    private PedidoHandler pedido = PedidoHandler.getInstance();
    private List<ComplementoPanel> panelesComplementos;

    /**
     * Creates new form SeleccionComplementosPanel
     */
    public SeleccionComplementosPanel(FrameRealizarPedido parent) {
        initComponents();

        this.parent = parent;

        this.jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        this.jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        this.listaComplementosPanel.setLayout(new BoxLayout(this.listaComplementosPanel, BoxLayout.Y_AXIS));

        MouseAdapter clickAction = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                //recalcularMontoTotal();
            }
        };

        this.addMouseListener(clickAction);

        this.cargarComplementos();
        //this.parent.actualizarMontoTotalDetallePedido();
    }

    /**
     * Carga en objetos de tipo "@OpcionComplementoDTO" las opciones que se 
     * eligieron en los paneles de tipo "@ComplementoPanel". Ademas de mostrar
     * el nuevo total generado a partir de esta eleccion.
     */
    public void recalcularMontoTotal() {

        if (this.panelesComplementos == null) {
            return;
        }

        this.pedido.getDetalleActual().complementos.clear();
        
        for (ComplementoPanel cmplPanel : this.panelesComplementos) {
            OpcionComplementoDTO opcion = cmplPanel.obtenerOpcionComplemento();
            if (opcion != null) {
                System.out.println("ahi ta %s...".formatted(opcion));
                this.pedido.getDetalleActual().complementos.add(opcion);
            }
        }

        //System.out.println("opciones: %s".formatted(this.pedido.getDetalleActual().complementos));
        //this.recalcularMontoTotal();
        //this.parent.actualizarMontoTotalDetallePedido();
    }

    /**
     * Carga los paneles de eleccion de complemento a traves de los complementos
     * que acepta el producto a personalizar.
     */
    private void cargarComplementos() {
        ProductoDTO producto = this.pedido.getDetalleActual().producto;

        if (producto != null) {

            this.panelesComplementos = new ArrayList<>();
            this.listaComplementosPanel.removeAll();

            for (ComplementoDTO compl : producto.getComplementosAceptados()) {
                ComplementoPanel panel = new ComplementoPanel(this.parent, this, compl);
                this.panelesComplementos.add(panel);
                this.listaComplementosPanel.add(panel);
            }

            this.listaComplementosPanel.revalidate();
            this.listaComplementosPanel.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaComplementosPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        siguientePanelBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(798, 592));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Complementos");

        javax.swing.GroupLayout listaComplementosPanelLayout = new javax.swing.GroupLayout(listaComplementosPanel);
        listaComplementosPanel.setLayout(listaComplementosPanelLayout);
        listaComplementosPanelLayout.setHorizontalGroup(
            listaComplementosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        listaComplementosPanelLayout.setVerticalGroup(
            listaComplementosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaComplementosPanel);

        siguientePanelBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        siguientePanelBtn.setText("Agregar Producto");
        siguientePanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientePanelBtnActionPerformed(evt);
            }
        });

        atrasBtn.setText("Atras");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atrasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguientePanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atrasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siguientePanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void siguientePanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientePanelBtnActionPerformed
        try {
            this.recalcularMontoTotal();
            Thread.sleep(500l);
            //this.parent.actualizarMontoTotalDetallePedido();
            //this.parent.mostrarConfirmacionAdicionProductoPanel();
        } catch (InterruptedException ex) {
            //Logger.getLogger(SeleccionComplementosPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_siguientePanelBtnActionPerformed

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        this.pedido.getDetalleActual().complementos.clear();
        //this.parent.actualizarMontoTotalDetallePedido();
        //this.parent.mostrarVariantesPanel();
    }//GEN-LAST:event_atrasBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listaComplementosPanel;
    private javax.swing.JButton siguientePanelBtn;
    // End of variables declaration//GEN-END:variables
}
