package mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.controlador.RealizarPedidoControlador;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.FrameRealizarPedido;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.util.PedidoHandler;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.OpcionComplementoDTO;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.ComplementoDTO;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.ProductoDTO;

/**
 * Panel que muestra todas las opciones de complemento disponibles en paneles 
 * de tipo "@ComplementoPanel".
 * @author Saul Neri
 */
public class SeleccionComplementosPanel extends javax.swing.JPanel {

    private RealizarPedidoControlador controlador;

    // Lista de los sub-paneles para poder preguntarles su estado
    private List<ComplementoPanel> panelesComplementos;

    /**
     * Constructor simple, se inicializa vacío.
     */
    public SeleccionComplementosPanel() {
        initComponents();
        this.panelesComplementos = new ArrayList<>();
        // Configura tu listaComplementosPanel con un BoxLayout o similar
        this.listaComplementosPanel.setLayout(new BoxLayout(this.listaComplementosPanel, BoxLayout.Y_AXIS));
    }

    public void setControlador(RealizarPedidoControlador controlador) {
        this.controlador = controlador;
    }

    /**
     * ¡NUEVO MÉTODO!
     * El controlador lo llama para poblar la lista.
     */
    public void cargarDatos(List<ComplementoDTO> complementosDisponibles) {
        // 1. Limpia datos anteriores
        this.listaComplementosPanel.removeAll();
        this.panelesComplementos.clear();

        // 2. Crea los nuevos sub-paneles (ya refactorizados)
        for (ComplementoDTO comp : complementosDisponibles) {
            ComplementoPanel panelComp = new ComplementoPanel(comp);
            this.panelesComplementos.add(panelComp);
            this.listaComplementosPanel.add(panelComp);
        }

        // 3. Refresca la UI
        this.listaComplementosPanel.revalidate();
        this.listaComplementosPanel.repaint();
    }

    // Botón "Siguiente"
    private void siguientePanelBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Recolecta los datos de los sub-paneles
        List<OpcionComplementoDTO> complementosSeleccionados = new ArrayList<>();
        for (ComplementoPanel panelComp : this.panelesComplementos) {
            OpcionComplementoDTO opcion = panelComp.obtenerOpcionComplemento();
            if (opcion != null) {
                complementosSeleccionados.add(opcion);
            }
        }

        // 2. Notifica al controlador
        if (this.controlador != null) {
            this.controlador.onComplementosSeleccionados(complementosSeleccionados);
        }
    }

    // Botón "Atrás"
    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Solo notifica al controlador.
        // El controlador decidirá si va a "variantes" o "tamanos".
        if (this.controlador != null) {
            this.controlador.onNavegarAtrasDesdeComplementos();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaComplementosPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        siguientePanelBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(798, 592));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Complementos");

        javax.swing.GroupLayout listaComplementosPanelLayout = new javax.swing.GroupLayout(listaComplementosPanel);
        listaComplementosPanel.setLayout(listaComplementosPanelLayout);
        listaComplementosPanelLayout.setHorizontalGroup(
            listaComplementosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        listaComplementosPanelLayout.setVerticalGroup(
            listaComplementosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaComplementosPanel);

        siguientePanelBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        siguientePanelBtn.setText("Agregar Producto");
        siguientePanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientePanelBtnActionPerformed(evt);
            }
        });

        atrasBtn.setText("Atras");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atrasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguientePanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atrasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siguientePanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listaComplementosPanel;
    private javax.swing.JButton siguientePanelBtn;
    // End of variables declaration//GEN-END:variables
}
