/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel;

        
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.ProductoDTO;
import mx.edu.itson.cafeteriauniversitaria.dtonegocios.TamanoDTO;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Set;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.controlador.RealizarPedidoControlador;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.util.ImageResizer;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.util.PedidoHandler;
import mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.FrameRealizarPedido;

/**
 * Panel que muestra las distintas elecciones de tamanos para el producto a personalizar.
 * @author Saul Neri
 */

public class TamanosPanel extends javax.swing.JPanel {

    private RealizarPedidoControlador controlador; // Referencia al controlador
    private TamanoDTO tamanoSeleccionado;
    private ButtonGroup grupoBotones;

    /**
     * ¡Constructor AHORA es simple!
     * Ya no recibe el producto ni el listener.
     */
    public TamanosPanel() {
        initComponents();
        this.grupoBotones = new ButtonGroup();
        // Se inicializa vacío
    }

    public void setControlador(RealizarPedidoControlador controlador) {
        this.controlador = controlador;
    }

    /**
     * ¡NUEVO MÉTODO!
     * El controlador llamará a esto para poblar el panel.
     */
    public void cargarDatos(Set<TamanoDTO> tamanos) {
        // 1. Limpia el panel de datos anteriores
        this.panelBotonesTamanos.removeAll();
        this.grupoBotones = new ButtonGroup(); // Reinicia el grupo
        this.tamanoSeleccionado = null;
        this.siguientePanelBtn.setEnabled(false);

        // 2. Crea los botones con los nuevos datos
        // (Este es tu código de antes, pero movido aquí)
        for (TamanoDTO tamano : tamanos) {
            // Asumo que tienes un panel custom "BotonTamanoProducto"
            // o simplemente un JRadioButton
            JRadioButton boton = new JRadioButton(tamano.nombre);
            
            boton.addActionListener(e -> {
                // Lógica interna de la vista:
                // solo guarda la selección localmente
                this.tamanoSeleccionado = tamano;
                this.siguientePanelBtn.setEnabled(true);
            });
            
            this.grupoBotones.add(boton);
            this.panelBotonesTamanos.add(boton);
        }

        // 3. Refresca la UI
        this.panelBotonesTamanos.revalidate();
        this.panelBotonesTamanos.repaint();
    }

    // El botón "siguiente" solo notifica al controlador
    private void siguientePanelBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (this.controlador != null && this.tamanoSeleccionado != null) {
            // El panel no sabe qué pasa después. Solo avisa.
            this.controlador.onTamanoSeleccionado(this.tamanoSeleccionado);
        }
    }

    // El botón "atrás" solo notifica
    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (this.controlador != null) {
            // El controlador decidirá qué panel mostrar
            this.controlador.onNavegarAtras("productos");
        }
    }


    /**
     * Habilita el boton para seguir a la pantalla de personalizacion siguiente.
     */
    public void habilitarBotonSiguiente() {
        this.siguientePanelBtn.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelBotonesTamanos = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));
        jPanel1 = new javax.swing.JPanel();
        siguientePanelBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();

        setName("panelSeleccionTamano"); // NOI18N
        setPreferredSize(new java.awt.Dimension(798, 592));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 96, 96));
        jLabel1.setText("Tamaños");

        siguientePanelBtn.setText("Siguiente");
        siguientePanelBtn.setEnabled(false);
        siguientePanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientePanelBtnActionPerformed(evt);
            }
        });

        atrasBtn.setText("Atras");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(atrasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguientePanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atrasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(siguientePanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotonesTamanos, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesTamanos, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBotonesTamanos;
    private javax.swing.JButton siguientePanelBtn;
    // End of variables declaration//GEN-END:variables
}
