/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.edu.itson.cafeteriauniversitaria.v1.mvc.realizarpedido.vista.panel;

import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;



/**
 * Panel que contiene las opciones de las distintas variantes del producto.
 * @author Saul Neri
 */
public class VariantesPanel extends javax.swing.JPanel {

    private List<String> variantes;
    private String varianteSeleccionada;
    
    private ButtonGroup variantesProductoGroup;
    
    /**
     * Creates new form VariantesPanel
     */
    public VariantesPanel(List<String> variantes) {
        initComponents();
        
        this.variantes = variantes;
        
        this.jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        this.jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        this.listaVariantesProducto.setLayout(new BoxLayout(this.listaVariantesProducto, BoxLayout.Y_AXIS));
        
        this.setupBotonesSeleccionVariante();
    }
    
    /**
     * Obtiene la variante seleccionada del grupo de JRadioButtons mostrado en el panel.
     * @return 
     */
    private String obtenerSeleccionVariante() {
        if (this.variantesProductoGroup != null) {
            for (AbstractButton button : java.util.Collections.list(this.variantesProductoGroup.getElements())) {
                if (button.isSelected()) {
                    return button.getText();
                }
            }
        }

        return null;
    }
    
    /**
     * Se crean los JRadioButton y los muestra en pantalla ademas de asociarlos al 
     * ButtonGroup para permitir solo la seleccion de una variante.
     */
    private void setupBotonesSeleccionVariante() {
        this.variantesProductoGroup = new ButtonGroup();

        this.listaVariantesProducto.removeAll();

        for (String variante: this.variantes) {
            JRadioButton btnVariante = new JRadioButton(variante);
            
            btnVariante.setFont(new Font("SansSerif", Font.BOLD, 18));
            
            btnVariante.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    varianteSeleccionada = obtenerSeleccionVariante();
                    //pedido.getDetalleActual().variante = varianteSeleccionada;
                    habilitarBotonSiguiente();
                    System.out.println("Seleccionada: " + varianteSeleccionada);
                }
            });
            
            this.variantesProductoGroup.add(btnVariante);
            this.listaVariantesProducto.add(btnVariante);
        }

        this.listaVariantesProducto.revalidate();
        this.listaVariantesProducto.repaint();
    }
    
    /**
     * Habilita el boton para pasar a la siguiente pantalla de personalizacion
     * del producto.
     */
    public void habilitarBotonSiguiente() {
        this.siguientePanelBtn.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        siguientePanelBtn = new javax.swing.JButton();
        atrasBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVariantesProducto = new javax.swing.JPanel(new FlowLayout(FlowLayout.LEFT));

        setPreferredSize(new java.awt.Dimension(798, 592));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Variantes");

        siguientePanelBtn.setText("Siguiente");
        siguientePanelBtn.setEnabled(false);
        siguientePanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientePanelBtnActionPerformed(evt);
            }
        });

        atrasBtn.setText("Atras");
        atrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(atrasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguientePanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(siguientePanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                    .addComponent(atrasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout listaVariantesProductoLayout = new javax.swing.GroupLayout(listaVariantesProducto);
        listaVariantesProducto.setLayout(listaVariantesProductoLayout);
        listaVariantesProductoLayout.setHorizontalGroup(
            listaVariantesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        listaVariantesProductoLayout.setVerticalGroup(
            listaVariantesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaVariantesProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBtnActionPerformed
        //this.parent.mostrarTamanosProductoPanel(pedido.getDetalleActual().producto);
    }//GEN-LAST:event_atrasBtnActionPerformed

    private void siguientePanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientePanelBtnActionPerformed
        //this.parent.mostrarComplementosPanel();
    }//GEN-LAST:event_siguientePanelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listaVariantesProducto;
    private javax.swing.JButton siguientePanelBtn;
    // End of variables declaration//GEN-END:variables
}
